spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/hamster_db"
    username: "postgres"
    password: "123456"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true

